GET http://localhost:3000
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:3000/helloworld
Accept: */*
Cache-Control: no-cache

###

GET http://localhost:3000/userlist
Accept: */*
Cache-Control: no-cache

###


GET http://localhost:3000/newuser
Accept: */*
Cache-Control: no-cache

###

POST http://localhost:3000/adduser
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"username":"testusername1","useremail":"useremail@qq.com"}

###

